version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vite-plugin-node-polyfills"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 10

